apiVersion: v1
kind: Namespace
metadata:
  name: ambientacion2
  labels:
    name: ambientacion2
    environment: production
  annotations:
    description: "Namespace for ambientacion-2 application"
